
cc_library(
    name = "func",
    srcs = ["Student2.cpp","AfterFirstSession.cpp","AfterYear.cpp"],
    hdrs = ["Student2.hpp","AfterFirstSession.hpp","AfterYear.hpp"],
    visibility = ["//visibility:public"],
)
