
cc_test(
    name = "tests",
    srcs = ["Test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Mtrx:Mtrx",
        "//src/Fraction:Fraction",
        "//src/List:List"
    ]
)
