
cc_library(
    name = "func",
    srcs = ["Tree.cpp", "ForestTree.cpp", "FruitTree.cpp","ContainerTrees.cpp"],
    hdrs = ["Tree.hpp", "ForestTree.hpp", "FruitTree.hpp","ContainerTrees.hpp"],
    visibility = ["//visibility:public"],
)
